name: productive_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  dartx: ^1.2.0
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.4
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.1
  uuid: ^4.5.1
  json_annotation: ^4.8.1
  audioplayers: ^5.2.1
  http: ^1.1.0
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.1
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/data/
    - assets/sounds/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product_Sans_Regular.ttf
        - asset: assets/fonts/Product_Sans_Bold.ttf
        - asset: assets/fonts/Product_Sans_Italic.ttf
          style: italic
        - asset: assets/fonts/Product_Sans_Bold_Italic.ttf
          style: italic
